CONSOLE_PREFIX = 'TelegramFreak:'
CONSOLE_MESSAGE_MAX_LENGTH = 40

BOT_MOD_PRIVATE = 'Private'
BOT_MOD_PUBLIC = 'Public'

REPLY_KEYBOARD_BUTTONS_IN_ROW = 3

BOT_NOTIFICATION_ACTIVATION = 'Bot is online.'
BOT_NOTIFICATION_DEACTIVATION = 'Bot is offline.'
